required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",

  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",
]

[[constraint]]
  # The dependency is used to generate client and deepcopy.
  branch = "master"
  name = "k8s.io/code-generator"

[[constraint]]
  branch = "release-1.7"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v4.0.0"

[[override]]
  name = "github.com/emicklei/go-restful"
  version = "v1.2"
